const ADD_BOOK = 1;
const GET_BOOKS = 2;
const CHANGE_ROLE = 3;
const DELETE_BOOK = 4;
const DELETE_USER = 5;
const DOWNLOAD_BOOK = 6;
const ADD_USER = 7;
const GET_USERS = 8;
const SEARCH_BOOK = 9;
const GET_USER_ID = 10;

const ADD_USER_BOOK = 11;
const EDIT_USER_PROFILE = 12;
const GET_USER_BOOK = 13;
const EDIT_USER = 14;

module.exports = {
    ADD_BOOK, GET_BOOKS,
    CHANGE_ROLE, DELETE_BOOK,
    DELETE_USER, DOWNLOAD_BOOK,
    ADD_USER, ADD_USER_BOOK,
    EDIT_USER_PROFILE, GET_USER_BOOK,
    GET_USERS, SEARCH_BOOK,
    GET_USER_ID,
    EDIT_USER
}